This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./Week12_Final_Report.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Week12_Final_Report.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (370 comparisons).
Generating output file Week12_Final_Report.acr....done (47 lines written, 0 warnings).
Output written in Week12_Final_Report.acr.
Transcript written in Week12_Final_Report.alg.
